

from Text_Summarizer.pipeline.stage_01_data_ingestion import DataIngestionTrainingPipeline
from Text_Summarizer.pipeline.stage_02_data_validation import DataValidationTrainingPipeline
from Text_Summarizer.pipeline.stage_03_data_transformation import DataTransformationTrainingPipeline
from Text_Summarizer.pipeline.stage_04_model_trainer import ModelTrainerTrainingPipeline
from Text_Summarizer.pipeline.stage_05_model_evaluation import ModelEvaluationTrainingPipeline
from Text_Summarizer.logging import logger